# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.
name: Release to latest/edge

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ci-tests:
    uses: ./.github/workflows/ci.yaml
    secrets: inherit
    permissions:
      contents: read
      actions: read # Needed by build workflow

  release:
    name: Release to Charmhub
    needs:
      - ci-tests
    uses: canonical/data-platform-workflows/.github/workflows/release_charm_edge.yaml@v53
    with:
      track: latest
      artifact-prefix: ${{ needs.ci-tests.outputs.artifact-prefix }}
    secrets:
      charmhub-token: ${{ secrets.CHARMHUB_TOKEN }}
    permissions:
      contents: write # Needed to create git tags
    cache-mode: none
